export Menujson=[
    {
            id:1,
            label:"home",
            icon:``
    },
    {       
            id:2,
            label:'activity',
            icon:``
    },
    {
            id:3,
            label:teams,
            icon:''
    },
    {
            id:4,
            label:'contact',
            icon:''
    },
    {
        id:5,
        label:'Dashboard',
        icon:''
    },
    {
        id:6,
        label:'setting',
        icon:''
    }
]